# Generated by Django 5.2 on 2025-04-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productquality',
            options={'verbose_name_plural': 'Product Qualities'},
        ),
        migrations.AlterField(
            model_name='productquality',
            name='broker_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productquality',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productquality',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productquality',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
